### ISSUE TITLE
添加device tree

### ISSUE THREAD

**Issue by Gstalker** [Gstalker/rustsbi-k510#2]
编译k510-buildroot并获取device tree source，将其移植到rustsbi-k510中

**Comment by duskmoon314** [comment]
我之前开了 [`k510-pac`](https://github.com/duskmoon314/k510-pac) 的坑，根据 zCore 那边的经验 `pac` 应该是可以和 devicetree 配合使用的。

现在基本只加了 uart、gpio、mtimer 和 plic，最近在忙别的事情搁置了。希望你感兴趣的话尝试一下，有啥需求也可以联系我。

😃
