### ISSUE TITLE
参考k510-buildroot实现sdcard-image构建链

### ISSUE THREAD

**Issue by Gstalker** [Gstalker/rustsbi-k510#3]

**Comment by luojia65** [comment]
我觉得我们需要把这块软件用xtask里面rust代码的形式重新编写一遍，你的看法是什么？

**Comment by Gstalker** [comment]
> 我觉得我们需要把这块软件用xtask里面rust代码的形式重新编写一遍，你的看法是什么？

能利用rust生态的东西是最好不过的，目前requirement.md里头提到的genimage是参照k510-buildroot的内容暂时存放，并非最终选择方向，目前第一目标是想办法跑起来
